name: TODO to Issue

on:
  push:
    paths:
      - "**/*.py"

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Environment Variables
        run: env
      - name: List Files
        run: ls -R
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: "todo"
