name: TODO to Issue

on:
  push:
    paths:
      - "**/*.py"

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "todo"
